config/routes.rb
Rails.application.routes.draw do
  get 'braintree/new'
  root 'welcome#index'
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]
  # resources :listings, controller: "listings" 
  #   resource :reservations
  # end

  resources :users, controller: "users", exclude: [:new] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
    resources :listings, exclude: [:index] do 
      resources :reservations, exclude: [:show, :index]
    end 
  end

  # resources :reservations, controller: "reservations"

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "users#new", as: "sign_up"
  get "/create_listings" => "listings#new", as: "create_listings"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/auth/:provider/callback" => "sessions#create_from_omniauth" 
  post "/listings/verify" => "listings#verify", as: "verify_listings"
  # get "/listings" => "listings#verify", as: "verified_listings"
  post "/listings/show/nav/:listing_id" => "listings#navigate", as: "navigate_listings" 
  get "/listings" => "listings#index", as: "listings"
  get "/yourlistings" => "listings#yourlistings", as: "yourlistings"
  get "/reservations/show" => "reservations#show", as: "reservations_for_homes"
  get "/yourreservations" =>"reservations#index", as: "your_reservations"
  # get "/listing/:id" => "listings#navigate", as: "navigate_listings" 
  post "braintree/checkout" 

end

app/models/reservation.rb
class Reservation < ApplicationRecord

	#before_create :check_date_availability
	validates_presence_of :start_date, :end_date
	#validates :start_date, presence: true
	#validates :end_date, presence: true
	validate :check_overlapping_dates, if: :check_error


	belongs_to :user
	belongs_to :listing

	def check_error
		self.errors.blank?
	end

	def check_overlapping_dates
		listing.reservations.each do |old_booking|
			if overlap?(self, old_booking)
				if self == old_booking
					return true

				else
					errors.add(:overlapping_dates, "the reservations dates conflict")
				end
			end
		end
	end

	def overlap?(x,y)
		if y.start_date != nil && y.end_date != nil
			(x.start_date - y.end_date).to_i * (y.start_date - x.end_date).to_i > 0
		end
	end

end

app/controllers/concerns/reservations_controller.rb
class ReservationsController < ApplicationController

	def new

		@listing
		@reservation = Reservation.new
	end 

	def create
		@reservations = current_user.reservations.new(new_reservations_params)
		if @reservations.save
			redirect_to listing_reservations
		end
	end

	def new_reservations_params
		params.require(:reservation).permit(:start_date, :end_date)
	end

	def index
		@listingid = current_user.reservations.listing_id
	end

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

	def new
		if !current_user
			flash[:notice] = "Please sign up or sign in before making a reservation."
		redirect_to sign_up_path
		else
		@listy = Listing.find(params[:listing_id])
		@reservation = Reservation.new
		end
	end 

	def create
		
		if !current_user
			flash[:notice] = "Please sign up or sign in before making a reservation."
			redirect_to sign_up_path

		else
		@reservations = current_user.reservations.new(new_reservations_params) 
		@reservations.listing_id = params[:listing_id]
		@thislisting = Listing.find(params[:listing_id]).user_id
		host = User.find(@thislisting) 
		receiver = host.email
		customer = current_user.email 
			if @reservations.save
				ReservationMailer.booking_email(receiver).deliver_now
				ReservationMailer.customer_booking(customer).deliver_now

				redirect_to user_listing_reservations_path

			else
				flash[:notice] = "Sorry, these booking dates are not available."

			end
		end


	end

	def new_reservations_params
		params.require(:reservation).permit(:start_date, :end_date)
	end



	def index
		if !current_user
			flash[:notice] = "Sorry. You don't have any reservations."
        	redirect_to listings_path
        else
		@reservations= Reservation.where(user_id: current_user.id) 

    	end
	end

	def show
		@owned_listings = Listing.where(user_id: current_user.id)
	end

end

app/views/reservations/index.html.erb
<h2>Your Reservations </h2>

<h3> <%= link_to "Make Payment", braintree_new_path %> </h3>
<br/>

<% @reservations.each do |x| %>
	<% @reserved_listing = Listing.find(x.listing_id) %>
	<%= @reserved_listing.name %>
	<br/>
	<%= @reserved_listing.description %>
	<br/><br/>
	<% @date = Reservation.find_by(user_id: current_user.id, listing_id: x.listing_id) %>
	<p><strong>Start date: </strong></p><%= @date.start_date %> <br/>
	<p><strong>End date: </strong></p><%= @date.end_date %>
	<br/>

	<% @reserved_listing.images.each do |individual| %>

		<img src= "<%= individual %>" class= "img-fluid" >	
	<% end %>
	<br/><hr/><hr/>
<% end %> 

app/views/reservations/new.html.erb
<h2>Make your booking (if you want)</h2>
<div>
<p><strong> Name: </strong> <%= @listy.name %> </p> 
<p><strong> Place: </strong><%= @listy.place_type %></p> 
<p><strong> Room Number: </strong> <%= @listy.room_number %> </p> 
<p><strong> Number of beds: </strong><%= @listy.bed_number %> </p> 
<p><strong> Max number of guests: </strong><%= @listy.guest_number %> </p> 
<p><strong> Country: </strong><%= @listy.country %> </p>
<p><strong> State: </strong><%= @listy.state %> </p>
<p><strong> City: </strong><%= @listy.city %> </p>
<p><strong> Zipcode </strong> <%= @listy.zipcode %> </p>
<p><strong> Address </strong> <%= @listy.address %> </p> 
<p>RM <%= @listy.price %></p> 
<p><strong> Description: </strong><%= @listy.description %></p>
	
	<% @userid = @listy.user_id %>
 <li> <strong>Host Contact:</strong>     <%= User.find(@userid).email %> </li>

<% @listy.images.each do |individual| %>

	<img src= "<%= individual.bigthumb.url %>" class= "img-fluid" >	
<% end %>
</div>

    		

<%= form_for [current_user, @listy, @reservation] do |form| %>
	<%= form.label :start_date %>
	<%= form.date_field :start_date %>
	<%= form.label :end_date %>
	<%= form.date_field :end_date %>


	<div class="submit-field">
      <%= form.submit %>
    </div>

<% end %>	

app/views/reservations/show.html.erb
<h2> Reservations Made For Your Properties </h2>

<% @owned_listings.each do |x| %>

<% if !Reservation.where(listing_id: x.id).empty? %>
		<% @property = Listing.find(x.id) %>
		<%= @property.name %>
		<br/>
		<%= @property.description %>
		<br/><br/>
		<% @date_time = Reservation.where(listing_id: x.id) %>
		<% @date_time.each do |y| %>
			<p><strong>Start date: </strong></p><%= y.start_date %> <br/>
			<p><strong>End date: </strong></p><%= y.end_date %><br/><br/>
		<% end %>

		<% @property.images.each do |individual| %>

			<img src= "<%= individual %>" class= "img-fluid" >	
		<% end %>
		<br/>

	<% end %>
<% end %>

		