config/routes.rb
Rails.application.routes.draw do
  get 'braintree/new'
  root 'welcome#index'
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]
  # resources :listings, controller: "listings" 
  #   resource :reservations
  # end

  resources :users, controller: "users", exclude: [:new] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
    resources :listings, exclude: [:index] do 
      resources :reservations, exclude: [:show, :index]
    end 
  end

  # resources :reservations, controller: "reservations"

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "users#new", as: "sign_up"
  get "/create_listings" => "listings#new", as: "create_listings"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/auth/:provider/callback" => "sessions#create_from_omniauth" 
  post "/listings/verify" => "listings#verify", as: "verify_listings"
  # get "/listings" => "listings#verify", as: "verified_listings"
  post "/listings/show/nav/:listing_id" => "listings#navigate", as: "navigate_listings" 
  get "/listings" => "listings#index", as: "listings"
  get "/yourlistings" => "listings#yourlistings", as: "yourlistings"
  get "/reservations/show" => "reservations#show", as: "reservations_for_homes"
  get "/yourreservations" =>"reservations#index", as: "your_reservations"
  # get "/listing/:id" => "listings#navigate", as: "navigate_listings" 
  post "braintree/checkout" 

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= javascript_include_tag 'application' %>
  <%= stylesheet_link_tag 'application' %>
  <%= csrf_meta_tag %>
<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
 
</head>

<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="http://localhost:3000/listings">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="http://localhost:3000/yourreservations">Your Reservations</a>
      </li>
      <% if current_user && !current_user.listings.empty? %>
        <li class="nav-item">
          <a class="nav-link" href="http://localhost:3000/yourlistings">Your Properties</a>
        </li>
      <%end%>

      <li class="nav-item">
        <a class="nav-link" href="http://localhost:3000/users/:user_id/listings/new">List Your Property!</a>
      </li>

      <% if current_user %>
      <li class="nav-item">
        <a class="nav-link disabled" href="http://localhost:3000/users/:id/edit"> Hello 
            <%= current_user.first_name %>
            <img src="<%= current_user.avatar.thumb.url %>">
          <% end %></a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

  

  <div id="flash">
    <% flash.each do |key, value| -%>
      <div id="flash_<%= key %>"><%=h value %></div>
    <% end %>
  </div>

          <div id="header">
            <% if signed_in? -%>
              <%= button_to t(".sign_out"), sign_out_path, method: :delete %>
            <% else -%>
              <%= link_to t(".sign_in"), sign_in_path %>
            <% end -%>
          </div>
  <%= yield %>
</body>
</html>